development:
  adapter: postgresql
  encoding: unicode
  database: cleaner_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: cleaner_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: cleaner_production
  pool: 5
  username: postgres
  password:
